### ISSUE TITLE
Add GitHub Topic: gitleaks

### ISSUE THREAD

**Issue by katrinleinweber** [eshork/gitleaks-action#1]
Thanks for publishing this! In case you'd like to make [your repo more findable](https://github.com/topics/gitleaks), you could [add that topic](https://help.github.com/articles/about-topics/) ;-) Thank you!

**Comment by eshork** [comment]
I'm glad that a few others found this quick project was useful.
However, I'm closing down this repo because the gitleaks project now publishes their own github action to wrap the tool.
I highly recommend you switch to that instead. You can find it at: https://github.com/marketplace/actions/gitleaks
